apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  clusterIP: None
  selector:
    {{- include "juiceshop.selectorLabels" . | nindent 8 }}
  ports:
    - port: {{ .Values.networking.containerPort }}
      targetPort: {{ .Values.networking.containerPort }}